from typing import Any, ClassVar

import nanobind

class ShapesDescriptor:
    construct: ClassVar[nanobind.nb_func] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def as_bytes(self) -> bytes: ...
    def __delattr__(self, name) -> Any: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __hash__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __setattr__(self, name, value) -> Any: ...
