import jax
from jax import numpy as jnp

from .jax_cuda_utils import make_cuda_primitive as make_cuda_primitive

def raysample(
    origins: jax.Array, directions: jax.Array, num_samples: int = ...
) -> jnp.ndarray: ...
def raysample_no_cuda(
    origins: jnp.ndarray, directions: jnp.ndarray, num_samples: int = ...
) -> jnp.ndarray: ...
