name: mypy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.8"
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          DISABLE_CMAKE_EXTENSIONS=1 pip install -e .
          pip install mypy
      - name: Test with mypy
        run: |
          mypy --install-types --non-interactive .
